apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hono-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/malathals/k8s-kustomization.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
