apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hono-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/malathals/k8s-kustomization.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
